
CREATE DATABASE DUMACODES;
USE   DUMACODES;

CREATE TABLE PERFIL
(
	 CH_ID_PERFIL CHAR(8) PRIMARY KEY NOT NULL,
     VC_NOMBRE VARCHAR(30)
);

CREATE TABLE DOCUMENTO_IDENTIDAD
(
	CH_ID_DOCUMENTO CHAR(8) PRIMARY KEY NOT NULL,
	VC_NOMBRE_DOCUMENTO VARCHAR(30)
);

CREATE TABLE USUARIO
(
	CH_ID_USUARIO CHAR(8) PRIMARY KEY NOT NULL,
    VC_PASSWORD VARCHAR(30),
    CH_ID_PERFIL CHAR(8),
    VC_NOMBRE VARCHAR(50),
    VC_APELLIDO_PATERNO VARCHAR(50),
    VC_APELLIDO_MATERNO VARCHAR(50),
    CH_ID_DOCUMENTO CHAR(8),
    CH_NUMERO_DOCUMENTO CHAR(8),
    VC_EMAIL VARCHAR(50)
);

ALTER TABLE USUARIO ADD CONSTRAINT FK_PERFIL  FOREIGN KEY (CH_ID_PERFIL) 
REFERENCES PERFIL(CH_ID_PERFIL);
ALTER TABLE USUARIO ADD CONSTRAINT FK_NUMERO_DOC FOREIGN KEY(CH_NUMERO_DOCUMENTO) 
REFERENCES DOCUMENTO_IDENTIDAD(CH_ID_DOCUMENTO);
